### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by maximpetrov** [RainixSTR/Java-PRICE-LIST#1]
1. По заданию цена продукта должна быть в рублях и копейках. Использовать для этого `double` крайне нежелательно, так как это чревато ошибками при округлении, что недопустимо в бухгалтерских расчётах.
1. https://github.com/RainixSTR/Java-PRICE-LIST/blob/b7c1c96dec13ab6fbf1ec3faad37858aed801f03/src/pricelist/PriceList.java#L96 Здесь просто можно вызвать `productList.hashCode()`.
1. В задании не уточнялось, задаётся код продукт вручную или генерируется, но в любом случае пользователь должен этот код знать. Сейчас Вы генерируете этот код, но снаружи его не узнать (`toString` не считается). При этом Вы ожидаете код в качестве аргумента в половине методов.

**Comment by maximpetrov** [comment]
1. Следует сделать getter'ы для полей `Product`.
1. В методах `setName` и `setPrice` Вы не проверяете существование объекта, что вызовет `NullPointerException`.
1. В методе `removeProduct` Вы никак не сообщаете пользователю, был ли объект действительно удалён.
1. Вообще, вместо явной проверки на наличие ключа, лучше пользоваться возвращаемым значением методов `putIfAbsent`, `get`, `remove` и т.д.
1. Стоимость в виде строки не самый удобный формат для дальнейшей обработки. Возможно, следовало бы сделать цену отдельным классом.
1. https://github.com/RainixSTR/Java-PRICE-LIST/blob/10ce036f7a044178369fbc6a9216653b0ddcf2f8/PRICE/src/pricelist/PriceList.java#L83-L86 Тут лучше использовать целочисленное деление и остаток от деления.
1. Не для всех методов у Вас есть тесты, например, `getPrice`.

**Comment by RainixSTR** [comment]
1. Добавил геттеры
2. Добавил проверку на существование объекта по id
3. Добавил вывод удаленного продукта в removeProduct
4. Можете немного уточнить. Не до конца понимаю про какие случаи вы говорите
5. Сделал цену отдельным классом Price
6. Исправил подсчет суммы
7. Добавил тесты для методов

**Comment by maximpetrov** [comment]
1. У класса `Price` не хватает методов `equals` и `hashCode`.
1. В классе `Price` не нужны сеттеры, конструктора достаточно.
1. Проверка корректности цены должна быть в конструкторе класса `Price`.
1. Имеет смысл для класса `Price` добавить конструктор из количества полного копеек, который будет переводить его в рубли и копейки. А ещё стоит добавить обратный метод, который вернёт цену в копейках.
1. Почему Вы снова вернулись к возвращению цены в `double`? У Вас же теперь есть класс `Price`.
1. Не вижу теста для полноценного `getPrice` (для нескольких единиц продукта).
1. По поводу пункта 4 из прошлого списка замечаний: везде, где Вы используете `checkId` перед внесением изменений, лучше обойтись без него, а использовать возвращаемое значение изменяющих методов.

**Comment by RainixSTR** [comment]
1. Добавил методы `equals` и `hashCode`
2. Убрал сеттеры
3. Добавил в класс `Price` проверку на корректность ввода
4. Добавил конструктор из копеек и обратный метод `getPriceInPenny`
5. Сделал возврат цены в переменной типа `Price`
6. Добавил тест
7. Убрал метод `checkId` и переписал методы

**Comment by maximpetrov** [comment]
1. Не совсем понятно, почему Вы вдруг поменяли поведение `addProduct` при наличии добавляемого кода в списке (возвращаемое значение вместо исключения), но это Ваше дело (хотя мне кажется, что это "более ошибочная" ситуация, чем удаление несуществующего объекта). Зато в этом методе Вы действительно обошлись одним поиском в `Map`. А вот в остальных случаях Вам этого не удалось. Если вызывать `get` несколько раз, то никакого выигрыша в производительности не будет, тогда уж проще и понятнее проверять наличие через `containsKey`, как Вы и делали. Я же хочу, чтобы Вы сохранили результат `get` в переменную, а потом его использовали. А в `removeProduct` вообще не нужен `get`, можно просто проверить `deletedProduct` на `null`.
1. Конструктор из копеек и обратный метод я попросил Вас сделать в первую очередь, чтобы Вы сами же ими и воспользовались в методе `getPrice`.

**Comment by RainixSTR** [comment]
1. В `addProduct` вернул вывод исключения. Создал переменную idList, в которую по мере добавления продуктов добавляется и их id, а так же метод checkIdInList, который проверяет существование id в данном листе. Соответственно добавил данный метод в качестве проверки в других методах
2. Исправил метод `getPrice`

**Comment by RainixSTR** [comment]
1. В addProduct вернул вывод исключения. Исправил методы.
2. Исправил метод getPrice

**Comment by RainixSTR** [comment]
1. В `addProduct` изменил поведение. Изменил методы, добавив переменную класса `Product`
2. Переделал метод `getPrice`

**Comment by maximpetrov** [comment]
https://github.com/RainixSTR/Java-PRICE-LIST/blob/7c734b1d79847f904365b31f1972f902fb59c297/PRICE/src/pricelist/PriceList.java#L121-L122 Почти всё. Не стоит делать `if` с пустым телом и `else`, просто инвертируйте условие. Наверняка даже Idea предлагает Вам это сделать.

**Comment by RainixSTR** [comment]
Исправил
